export const countryCityOptions = {
  China: [
    "Shanghai",
    "Beijing",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Chongqing",
    "Hangzhou",
    "Wuhan",
    "Xi'an",
    "Nanjing",
    "Suzhou",
    "Tianjin",
    "Zhengzhou",
    "Changsha",
    "Dongguan",
    "Foshan",
    "Ningbo",
    "Qingdao",
    "Shenyang",
    "Hefei",
    "Jinan",
    "Fuzhou",
    "Xiamen",
    "Kunming",
    "Dalian",
    "Wuxi",
    "Harbin",
    "Changchun",
    "Nanchang",
    "Nanning",
    "Guiyang",
    "Shijiazhuang",
    "Taiyuan",
    "Hohhot",
    "Lanzhou",
    "Urumqi",
    "Haikou",
    "Sanya",
    "Wenzhou",
    "Jinhua",
    "Quanzhou",
    "Zhuhai",
    "Zhongshan",
    "Huizhou",
    "Nantong",
    "Changzhou",
    "Xuzhou",
    "Yantai",
    "Weihai",
    "Tangshan",
    "Luoyang",
  ],
  France: ["Paris", "Lyon", "Marseille", "Nice", "Toulouse", "Bordeaux", "Lille", "Nantes", "Strasbourg", "Montpellier", "Grenoble", "Rennes"],
  Germany: ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Dusseldorf", "Stuttgart", "Leipzig", "Dresden", "Heidelberg", "Aachen", "Bonn"],
  Italy: ["Milan", "Rome", "Florence", "Turin", "Bologna", "Venice", "Naples", "Pisa", "Padua", "Genoa"],
  Spain: ["Barcelona", "Madrid", "Valencia", "Seville", "Malaga", "Granada", "Bilbao", "Zaragoza", "Salamanca"],
  UK: ["London", "Manchester", "Edinburgh", "Birmingham", "Glasgow", "Leeds", "Liverpool", "Bristol", "Sheffield", "Nottingham", "Cambridge", "Oxford", "Coventry", "Newcastle"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Delft", "Leiden", "Groningen", "Maastricht"],
  Belgium: ["Brussels", "Antwerp", "Ghent", "Leuven", "Liege"],
  Switzerland: ["Zurich", "Geneva", "Lausanne", "Basel", "Bern", "St. Gallen", "Lugano"],
  Austria: ["Vienna", "Graz", "Salzburg", "Innsbruck", "Linz"],
  Ireland: ["Dublin", "Cork", "Galway", "Limerick"],
  Portugal: ["Lisbon", "Porto", "Coimbra", "Braga"],
  Sweden: ["Stockholm", "Gothenburg", "Lund", "Uppsala", "Malmo"],
  Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  Finland: ["Helsinki", "Espoo", "Tampere", "Turku", "Oulu"],
  Norway: ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  Poland: ["Warsaw", "Krakow", "Wroclaw", "Gdansk", "Poznan"],
  Czechia: ["Prague", "Brno", "Ostrava"],
  Hungary: ["Budapest", "Debrecen", "Szeged"],
  Greece: ["Athens", "Thessaloniki", "Patras"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Gold Coast", "Hobart", "Darwin", "Newcastle", "Wollongong"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Ottawa", "Calgary", "Edmonton", "Waterloo", "Hamilton", "Quebec City", "Winnipeg", "Victoria", "Halifax"],
  USA: ["New York", "Los Angeles", "San Francisco", "San Jose", "Seattle", "Boston", "Chicago", "Washington DC", "Philadelphia", "Atlanta", "Austin", "Dallas", "Houston", "Miami", "Orlando", "San Diego", "Irvine", "Berkeley", "Palo Alto", "Ann Arbor", "Madison", "Pittsburgh", "Minneapolis", "Denver", "Phoenix", "Portland"],
} as const;

export type CountryName = keyof typeof countryCityOptions;

export const countries = Object.keys(countryCityOptions) as CountryName[];

const countryLabelsZh: Record<string, string> = {
  China: "中国",
  France: "法国",
  Germany: "德国",
  Italy: "意大利",
  Spain: "西班牙",
  UK: "英国",
  Netherlands: "荷兰",
  Belgium: "比利时",
  Switzerland: "瑞士",
  Austria: "奥地利",
  Ireland: "爱尔兰",
  Portugal: "葡萄牙",
  Sweden: "瑞典",
  Denmark: "丹麦",
  Finland: "芬兰",
  Norway: "挪威",
  Poland: "波兰",
  Czechia: "捷克",
  Hungary: "匈牙利",
  Greece: "希腊",
  Australia: "澳大利亚",
  Canada: "加拿大",
  USA: "美国",
};

const cityLabelsZh: Record<string, string> = {
  Shanghai: "上海",
  Beijing: "北京",
  Guangzhou: "广州",
  Shenzhen: "深圳",
  Chengdu: "成都",
  Chongqing: "重庆",
  Hangzhou: "杭州",
  Wuhan: "武汉",
  "Xi'an": "西安",
  Nanjing: "南京",
  Suzhou: "苏州",
  Tianjin: "天津",
  Zhengzhou: "郑州",
  Changsha: "长沙",
  Dongguan: "东莞",
  Foshan: "佛山",
  Ningbo: "宁波",
  Qingdao: "青岛",
  Shenyang: "沈阳",
  Hefei: "合肥",
  Jinan: "济南",
  Fuzhou: "福州",
  Xiamen: "厦门",
  Kunming: "昆明",
  Dalian: "大连",
  Wuxi: "无锡",
  Harbin: "哈尔滨",
  Changchun: "长春",
  Nanchang: "南昌",
  Nanning: "南宁",
  Guiyang: "贵阳",
  Shijiazhuang: "石家庄",
  Taiyuan: "太原",
  Hohhot: "呼和浩特",
  Lanzhou: "兰州",
  Urumqi: "乌鲁木齐",
  Haikou: "海口",
  Sanya: "三亚",
  Wenzhou: "温州",
  Jinhua: "金华",
  Quanzhou: "泉州",
  Zhuhai: "珠海",
  Zhongshan: "中山",
  Huizhou: "惠州",
  Nantong: "南通",
  Changzhou: "常州",
  Xuzhou: "徐州",
  Yantai: "烟台",
  Weihai: "威海",
  Tangshan: "唐山",
  Luoyang: "洛阳",
  Paris: "巴黎",
  Lyon: "里昂",
  Marseille: "马赛",
  Nice: "尼斯",
  Toulouse: "图卢兹",
  Bordeaux: "波尔多",
  Lille: "里尔",
  Nantes: "南特",
  Strasbourg: "斯特拉斯堡",
  Montpellier: "蒙彼利埃",
  Grenoble: "格勒诺布尔",
  Rennes: "雷恩",
  Berlin: "柏林",
  Munich: "慕尼黑",
  Frankfurt: "法兰克福",
  Hamburg: "汉堡",
  Cologne: "科隆",
  Dusseldorf: "杜塞尔多夫",
  Stuttgart: "斯图加特",
  London: "伦敦",
  Manchester: "曼彻斯特",
  Edinburgh: "爱丁堡",
  Birmingham: "伯明翰",
  Glasgow: "格拉斯哥",
  Cambridge: "剑桥",
  Oxford: "牛津",
  Milan: "米兰",
  Rome: "罗马",
  Florence: "佛罗伦萨",
  Venice: "威尼斯",
  Barcelona: "巴塞罗那",
  Madrid: "马德里",
  Amsterdam: "阿姆斯特丹",
  Rotterdam: "鹿特丹",
  Brussels: "布鲁塞尔",
  Zurich: "苏黎世",
  Geneva: "日内瓦",
  Vienna: "维也纳",
  Dublin: "都柏林",
  Lisbon: "里斯本",
  Stockholm: "斯德哥尔摩",
  Copenhagen: "哥本哈根",
  Helsinki: "赫尔辛基",
  Oslo: "奥斯陆",
  Warsaw: "华沙",
  Prague: "布拉格",
  Budapest: "布达佩斯",
  Athens: "雅典",
  Sydney: "悉尼",
  Melbourne: "墨尔本",
  Brisbane: "布里斯班",
  Perth: "珀斯",
  Adelaide: "阿德莱德",
  Canberra: "堪培拉",
  Toronto: "多伦多",
  Vancouver: "温哥华",
  Montreal: "蒙特利尔",
  Ottawa: "渥太华",
  Calgary: "卡尔加里",
  Edmonton: "埃德蒙顿",
  Waterloo: "滑铁卢",
  "New York": "纽约",
  "Los Angeles": "洛杉矶",
  "San Francisco": "旧金山",
  "San Jose": "圣何塞",
  Seattle: "西雅图",
  Boston: "波士顿",
  Chicago: "芝加哥",
  "Washington DC": "华盛顿",
  Philadelphia: "费城",
  Atlanta: "亚特兰大",
  Austin: "奥斯汀",
  Dallas: "达拉斯",
  Houston: "休斯敦",
  Miami: "迈阿密",
  "San Diego": "圣迭戈",
};

export function citiesFor(country: CountryName) {
  return [...countryCityOptions[country]];
}

export function countryLabel(country: CountryName, language: "en" | "zh") {
  return language === "zh" ? countryLabelsZh[country] || country : country;
}

export function cityLabel(city: string, language: "en" | "zh") {
  return language === "zh" ? cityLabelsZh[city] || city : city;
}

export function routeFromParts(fromCity: string, toCity: string) {
  return `${fromCity} → ${toCity}`;
}
